---
title: "Full_Log_Reg"
format: html
---

```{r}
library(tidyverse)
library(janitor)
library(caret)
library(ROCR)
```

```{r}
bank <- read_delim("../data/bank-additional-full.csv", delim = ";", 
                   show_col_types = FALSE) %>%
  clean_names() %>%
  mutate_if(is.character, as.factor)
```

```{r}
set.seed(123)
train_index <- createDataPartition(bank$y, p = 0.8, list = FALSE)
train <- bank[train_index, ]
test <- bank[-train_index, ]
```

```{r}
# Basic logistic model using all predictors
logit_model <- glm(y ~ ., data = train, family = binomial)

# View summary
summary(logit_model)
```

```{r}
# Predict probabilities and classes
test$pred_prob <- predict(logit_model, newdata = test, type = "response")
test$pred_class <- ifelse(test$pred_prob > 0.5, "yes", "no")

# Confusion matrix
confusionMatrix(factor(test$pred_class, levels = c("no", "yes")),
                test$y, positive = "yes")
```

```{r}
roc.predictions <- prediction(test$pred_prob, test$y)

roc.perf <- performance(roc.predictions, "tpr", "fpr")

plot(roc.perf, col = "blue", lwd = 2, main = "ROC", print.thres = TRUE)
abline(a = 0, b = 1, col = "black", lty = 2)

auc <- performance(roc.predictions, "auc")
auc@y.values[[1]]
```
